from .AcademyModel import AcademyModel
from .CityModel import CityModel
from .CountryModel import CountryModel
from .DepartmentModel import DepartmentModel
from .DeveloperModel import DeveloperModel
from .EducationModel import EducationModel
from .EducationTypeModel import EducationTypeModel
from .LanguageModel import LanguageModel
from .ProjectModel import ProjectModel
from .SkillModel import SkillModel
from .TechnologyModel import TechnologyModel